{
  "cols": [
    {"id": "fullname",     "label": "Nom",    "type": "string"},
    {"id": "units",        "label": "Unité",        "type": "number"},
    {"id": "quota-share",  "label": "Parts",  "type": "number"},
    {"id": "role",         "label": "Role",         "type": "string"},
    {"id": "registration", "label": "Enregistrement", "type": "string"},
    {"id": "status",       "label": "Status",       "type": "string"}
    <?php if (true == ($showDashboard = $this->members()->showDashboard($this->members, $this->acl))): ?>,
    {"id": "dashboard",    "label": "Tableau de bord",    "type": "number"}
    <?php endif; ?>],
   "rows": [
<?php $i = 0; ?>
<?php foreach ($this->members as $member): ?>
     {"c":[
       {"v": "<?= $this->members()->getProfileLink($member) ?>"},
       {"v":<?php $stats = $member->getStats(); echo $stats['unitNb'] ?>, "f":"<?= $stats['unitNb'] ?>"},
       {"v":<?= $stats['shareP'] ?>, "f":"<?= $stats['shareP'] ?>"},
       {"v":"<?= $member->role ?>"},
       {"v":"<?= $member->enrollement_date ?>", "p":{"className": "center-text google-visualization-table-td"}},
       {"v":"<?= $this->members()->getStatus($member); ?>", "p":{"style": "<?= $this->members()->getStatusCss($member); ?>"}}
<?php if (true === $showDashboard): ?>
       ,{"v":"<?= $this->members()->getDashboard($member, $this->acl); ?>", "p":{"className": "center-text google-visualization-table-td"}}
<?php endif; ?>
       ]}<?= ($i++ != count($this->members) + count($this->pendingMembers) - 1) ? ',' : ''; ?>
<?php endforeach;?>

<?php foreach ($this->pendingMembers as $member): ?>
     {"c":[
       {"v": "<?= $this->members()->getProfileLink($member) ?>"},
       {"v":2300, "f":"$10.000"},
       {"v":213, "f":"$10.000"},
       {"v":"<?= $member->role ?>"},
       {"v":"<?= $member->enrollement_date ?>", "p":{"className": "center-text google-visualization-table-td"}},
       {"v":"<?= $this->members()->getStatus($member); ?>", "p":{"style": "<?= $this->members()->getStatusCss($member); ?>"}}
<?php if (true === $showDashboard): ?>
       ,{"v":"<?= $this->members()->getDashboard($member, $this->acl); ?>", "p":{"className": "center-text google-visualization-table-td"}}
<?php endif; ?>
       ]}<?= ($i++ != count($this->members) + count($this->pendingMembers) - 1) ? ',' : ''; ?>

<?php endforeach; ?>

  ]
}