<?= $this->doctype()    . PHP_EOL; ?>
<html>
<head>
<?= $this->headTitle()  . PHP_EOL; ?>
<?= $this->headMeta()   . PHP_EOL; ?>
<?= $this->headLink()   . PHP_EOL; ?>
<?= $this->headScript() . PHP_EOL; ?>
<?= $this->jQuery() ?>
<?= $this->headStyle()  . PHP_EOL; ?>
</head>
<body>
<?= $this->partial('partials/_header.phtml'); ?>
<?php if ($this->layout()->nestedLayout): ?>
<?php   $this->layout()->setLayout($this->layout()->nestedLayout); ?> 
<?php else: ?> 
<?php   $this->layout()->setLayout('defaultLayout'); ?> 
<?php endif;?>
<?= $this->layout()->render(); ?> 
<?= $this->partial('partials/_footer.phtml'); ?>
<?= $this->inlineScript(); ?>


<?php if (APPLICATION_ENV == "development") {
$bootstrap = Zend_Controller_Front::getInstance()->getParam('bootstrap');
$execTime = (microtime(true) - $bootstrap->getResource('profiling')) * 1000;
$db = $bootstrap->getResource('db');
$profiler = $db->getProfiler();
$totalTime    = $profiler->getTotalElapsedSecs();
$queryCount   = $profiler->getTotalNumQueries();
$longestTime  = 0;
$longestQuery = null;
$allQuery = "";
echo '<div style="background-color: #bbb; margin-top:4px; ">';
echo '<div style="margin:20px; float: right;"><img src="http://chart.googleapis.com/chart?cht=qr&chs=150x150&chld=L|0&chl=' . 
			Zend_Controller_Front::getInstance()->getRequest()->getScheme() . 
			'://' . Zend_Controller_Front::getInstance()->getRequest()->getHttpHost() .
			Zend_Controller_Front::getInstance()->getRequest()->getRequestUri() . '"></div>';
echo 'PHP Debug:<br />';
echo 'Memory used: ' . (memory_get_peak_usage(true) / 1024) . ' KB (Peak)<br />';
echo 'Memory used: ' . (memory_get_usage(true) / 1024) . ' KB (Current)<br />';
echo "Executed in " . round($execTime, 3) . " ms<br /><br />"; 
$cs = Zend_Registry::get('Construct_stats');
echo "Constructor Count:<br />";
foreach ($cs as $k => $val)
	echo "$k: $val<br />";
echo "<br />";
echo 'SQL Debug:<br />';
$opts = $bootstrap->getOptions();
echo $opts['resources']['db']['params']['host'] . " : " . $opts['resources']['db']['params']['dbname'] . " (" . $opts['resources']['db']['adapter'] . ")<br />";
echo 'Executed ' . $queryCount . ' queries in ' . round($totalTime * 1000, 3) .
     ' ms' . "<br />\n";
if ($profiler->getQueryProfiles())
{
foreach ($profiler->getQueryProfiles() as $query) {
    if ($query->getElapsedSecs() > $longestTime) {
        $longestTime  = $query->getElapsedSecs();
        $longestQuery = $query->getQuery();
    }
    $allQuery .= sprintf("(%.3f ms) ", ($query->getElapsedSecs() * 1000)) . $query->getQuery() . "<br />";
}
echo 'Average query length: ' . round($totalTime * 1000 / $queryCount, 3) .
     ' ms' . "<br />\n";
echo 'Queries per second: ' . round($queryCount / $totalTime)  . "<br />\n";
echo 'Longest query length: ' . round($longestTime * 1000, 3) . " ms<br />\n";
echo "Longest query: " . $longestQuery  . "<br />\n";
echo "List of all Queries :<hr />" . $allQuery;
}

echo "<br />Cache Debug:<br />";
$cache = Ivc_Cache::getInstance();
$cacheStats = $cache->getStats();
echo "Executed " . count($cacheStats) . " queries<br />";
echo "List of all Cache Queries<hr />";

echo "<table width=400px>";
foreach ($cacheStats as $val)
{
    echo "<tr><td>";
    echo $val['full_key'] . "</td><td>" . $val['action'] . "</td><td>" . $val['size'] . " B";
    echo "</td></tr>";
}
echo "</table>";
echo "<br />ACL Debug:<hr />";
Zend_Registry::get('Ivc_Acl')->printRoleTree('guest', 0);
echo "</div>";
}
?>



<!-- begin olark code -->
<script data-cfasync="false" type='text/javascript'>/*<![CDATA[*/window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){
f[z]=function(){
(a.s=a.s||[]).push(arguments)};var a=f[z]._={
},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){
f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={
0:+new Date};a.P=function(u){
a.p[u]=new Date-a.p[0]};function s(){
a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){
hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){
return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){
b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{
b.contentWindow[g].open()}catch(w){
c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{
var t=b.contentWindow[g];t.write(p());t.close()}catch(x){
b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({
loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
/* custom configuration goes here (www.olark.com/documentation) */
olark.identify('9468-173-10-1761');/*]]>*/</script>
<noscript><a href="https://www.olark.com/site/9468-173-10-1761/contact"
	title="Contact us" target="_blank">Questions? Feedback?</a></noscript>
<!-- end olark code -->

<script type='text/javascript'>
   olark.configure('locale.welcome_title', "Tchatter avec nous!");
   olark.configure('locale.chatting_title', "Actuellement en communication");
   olark.configure('locale.unavailable_title', "Envoyez-nous un message");
   olark.configure('locale.busy_title', "Status: Occupé");
   olark.configure('locale.away_message', "Nous sommes actuellement hors-ligne, n'hésitez pas à nous envoyer un message.");
   olark.configure('locale.loading_title', "Chargement d'Olark...");
   olark.configure('locale.welcome_message', "Nous sommes en ligne ! N'hésitez pas à parler avec nous.");
   olark.configure('locale.busy_message', "Nous sommes occupés, veuillez attendre quelques minutes s'il vous plaît.");
   olark.configure('locale.chat_input_text', "Tapez votre message ici...");
   olark.configure('locale.name_input_text', " et tapez votre Nom");
   olark.configure('locale.email_input_text', " et tapez votre E-mail");
   olark.configure('locale.offline_note_message', "Votre message...");
   olark.configure('locale.send_button_text', "Envoyer");
   olark.configure('locale.offline_note_thankyou_text', "Merci pour votre message. Nous reviendrons vers vous dès que possible.");
   olark.configure('locale.offline_note_error_text', "Vous devez remplir tous les champs.");
   olark.configure('locale.offline_note_sending_text', "Envoi en cours...");
   olark.configure('locale.operator_is_typing_text', "est en train d'écrire...");
   olark.configure('locale.operator_has_stopped_typing_text', "a arrêter d'écrire");
   olark.configure('locale.introduction_error_text', "Merci de laissez votre nom et e-mail afin que l'on puisse vous recontacter.");
   olark.configure('locale.introduction_messages', "Bienvenu, cliquez sur 'Démarrer la conversation' pour nous parler.");
   olark.configure('locale.introduction_submit_button_text', "Démarrer la conversation");
   olark.configure('locale.disabled_input_text_when_convo_has_ended', "fin de la conversation, rafraichir pour une nouvelle conversation");
   olark.configure('locale.disabled_panel_text_when_convo_has_ended', "Cette conversation est finie, rafraichissez la page pour en démarrer une nouvelle.");
   olark.configure('locale.name_input_text', "Votre nom...");
   olark.configure('locale.phone_input_text', "Votre numéro de téléphone...");
   olark.configure('locale.email_input_text', "Votre e-mail...");
   olark.configure('locale.send_button_text', "Envoyer");

</script>

</body>
</html>